# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "demo-useast-container"
    key                  = "components/network/terraform.tfstate"
    resource_group_name  = "demo-useast-state-rg"
    storage_account_name = "demostatestore"
  }
}
